### ISSUE TITLE
option extra_http_headers isn't working properly

### ISSUE THREAD

**Issue by jewilmeer** [sanzstez/gotenberg-ruby#3]
Hi,

Thanks for the awesome gem, almost works like a charm! I'm trying to add an authorization header so my google cloud run works authorized, but when setting the extra header it seems like it just adds it to the user agent string instead.

I'm using the following code:

```ruby
document = Gotenberg::Chromium.call(target_url) do |doc|
  doc.html html
  doc.extra_http_headers({ 'Authorization' => "Bearer #{authorizer.id_token}" })
end
```

When inspecting the resulting document I noticed this was a bit weird: 
```ruby
[1] pry(main)> document
=> #<Gotenberg::Chromium:0x000000010630b310
 @base_path="https://gotenberg-3h234zupza-ez.a.run.app",
 @endpoint="/forms/chromium/convert/html",
 @exception=#<Gotenberg::TransformError: the server responded with status 403>,
 @files=[#<Multipart::Post::UploadIO:0x0000000105b56778 @content_type="text/html", @io=#<StringIO:0x000000010630a898>, @local_path="local.path", @opts={}, @original_filename="index.html">],
 @headers={},
 @metadata={},
 @properties=
  {"userAgent"=>
    "{\"Authorization\":\"Bearer eyJ...."}"}>
```

Looking at [the source](https://github.com/sanzstez/gotenberg-ruby/blob/master/lib/gotenberg/chromium/properties.rb#L94-L98), the result make sense. I'll try to figure out how to set it properly.

**Comment by jewilmeer** [comment]
I've found that changing the method to this would work:

```
      def extra_http_headers extra_headers
        extra_headers.each do |key, value|
          headers[key] = value.to_s
        end

        self
      end
```

Will create a PR tomorrow.

**Comment by sanzstez** [comment]
@jewilmeer Hello! I looked code and agree with you - it’s was a pity copy-paste bug :( 
I will wait for your PR and make new release as soon as possible.
Thanks for you contribution!

**Comment by sanzstez** [comment]
Good morning! 
I have added missed functionality in this PR https://github.com/sanzstez/gotenberg-ruby/pull/5
So now you can use 2 ways to do what you need:

Pass additional headers for faraday client instance (Authorization, User-Agent, etc.):

```ruby
document = Gotenberg::Chromium.call(ENV['GOTENBERG_URL'], headers: { 'Authorization': 'Bearer token123' }) do |doc|
  doc.url 'https://my.url'
end
```

OR

```ruby
document = Gotenberg::Chromium.call(ENV['GOTENBERG_URL']) do |doc|
  doc.url 'https://my.url'
  doc.client_extra_http_headers({ 'Authorization': 'Bearer token123' })
end
```

I close this issue and your PR as done. Version 1.0.12 was released to rubygems.
Thank you @jewilmeer very much for you contribution! Have a good day!

**Comment by jewilmeer** [comment]
Looks good, thanks for the new version, and additional documentation. Have a nice weekend!
